trigger:
  branches:
    only:
      - main
  tags:
    only:
      - v*
  manual:
    branches:
      - "**"

environment:
  xcode: "15.4"
  vars:
    APP_NAME: "VlessBox"

workflows:
  ios-workflow:
    name: VlessBox iOS Build
    max_build_duration: 60

    scripts:
      - name: Setup environment
        script: |
          xcodebuild -version
          swift --version
          pwd
          ls -la

      - name: Build IPA
        script: |
          pwd
          ls -la
          xcodebuild archive \\
            -scheme VlessBox \\
            -project VlessBox.xcodeproj \\
            -xcconfig Release.xcconfig \\
            -archivePath "C:\Users\Administrator/BuildArtifacts/VlessBox.xcarchive" \\
            SKIP_INSTALL=NO \\
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES

    artifacts:
      - BuildArtifacts/VlessBox.xcarchive
      - C:\Users\Administrator/Library/Developer/Xcode/DerivedData/**/Logs/XcodeBuild.log
